#!/bin/sh
if [ -n "$HOME" ];then
    cp -n /etc/xdg/kglobalshortcutsrc $HOME/.config/kglobalshortcutsrc
fi

EXECUTE_PATH=$(cd `dirname $0`; pwd)

export QT_LOGGING_RULES="*=true"
export "LD_PRELOAD=/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libdde-kwin-xcb.so:$LD_PRELOAD"
export QT_SCALE_FACTOR=1
#":"后的"appFilePath=..."会传递给QPlatformIntegration::create调用
# appFilePath 的值会覆盖 QCoreApplication::applicationPath，以确保kwin崩溃自动重启时也是启动的kwin_no_scale脚本
kwin_x11 -platform dde-kwin-xcb:appFilePath=$EXECUTE_PATH/kwin_no_scale $@ 2> /home/$USER/kwin.log
